package com.titan.auth.sys.core.profissional.domain.enums;

public enum ProfissaoEspecializada {

	ASSISTENTE_SOCIAL,
	BIOLOGO,
	DENTISTA,
	EDUCADOR_FISICO,
	ENFERMEIRO,
	FARMACEUTICO,
	FISIOTERAPEUTA,
	FONOAUDIOLOGO,
	MEDICO,
	MASSOTERAPEUTA,
	NUTRICIONISTA,
	PSICOLOGO,
	TERAPEUTA_OCUPACIONAL,
	TERAPEUTA_HOLISTICO,
	OUTRO
	
}
